from __future__ import annotations

from pathlib import Path
from typing import Any

from .util import safe_output_path


class OfficeArtifactService:
    """Create basic Office artifacts behind an approval-gated agent tool.

    Production deployments can replace this adapter with Microsoft Graph,
    LibreOffice automation, a template engine, or a richer artifact service.
    The knowledge-base importers are independent of the writer implementation.
    """

    def __init__(self, project_root: str | Path):
        self.project_root = Path(project_root).resolve()

    def export_word(
        self,
        output_path: str,
        title: str,
        sections: list[dict[str, Any]],
    ) -> dict[str, Any]:
        from docx import Document
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.shared import Inches, Pt

        destination = safe_output_path(self.project_root, output_path)
        if destination.suffix.lower() != ".docx":
            raise ValueError("Word output path must end with .docx")
        document = Document()
        section = document.sections[0]
        section.top_margin = Inches(0.8)
        section.bottom_margin = Inches(0.8)
        section.left_margin = Inches(0.9)
        section.right_margin = Inches(0.9)
        title_paragraph = document.add_paragraph()
        title_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = title_paragraph.add_run(title)
        run.bold = True
        run.font.size = Pt(22)
        for item in sections:
            heading = item.get("heading")
            if heading:
                document.add_heading(str(heading), level=int(item.get("level", 1)))
            for paragraph in item.get("paragraphs", []):
                document.add_paragraph(str(paragraph))
            for bullet in item.get("bullets", []):
                document.add_paragraph(str(bullet), style="List Bullet")
            table_rows = item.get("table") or []
            if table_rows:
                width = max(len(row) for row in table_rows)
                table = document.add_table(rows=0, cols=width)
                table.style = "Table Grid"
                for row_index, values in enumerate(table_rows):
                    cells = table.add_row().cells
                    for column_index, value in enumerate(values):
                        cells[column_index].text = str(value)
                        if row_index == 0:
                            for cell_run in cells[column_index].paragraphs[0].runs:
                                cell_run.bold = True
        document.core_properties.title = title
        document.core_properties.subject = "Generated by Creative Claw"
        document.save(destination)
        return {"path": str(destination), "kind": "docx", "section_count": len(sections)}

    def edit_word(
        self,
        path: str,
        replacements: dict[str, str] | None = None,
        append_sections: list[dict[str, Any]] | None = None,
    ) -> dict[str, Any]:
        """Apply explicit text replacements and append sections to a Word file."""

        from docx import Document

        destination = safe_output_path(self.project_root, path)
        if destination.suffix.lower() != ".docx" or not destination.is_file():
            raise FileNotFoundError(f"Word document not found: {destination}")
        document = Document(destination)
        replacements = replacements or {}
        replaced = 0

        def replace_in_paragraph(paragraph) -> None:  # noqa: ANN001
            nonlocal replaced
            original = paragraph.text
            updated = original
            for old, new in replacements.items():
                occurrences = updated.count(old)
                if occurrences:
                    updated = updated.replace(old, new)
                    replaced += occurrences
            if updated != original:
                paragraph.text = updated

        for paragraph in document.paragraphs:
            replace_in_paragraph(paragraph)
        for table in document.tables:
            for row in table.rows:
                for cell in row.cells:
                    for paragraph in cell.paragraphs:
                        replace_in_paragraph(paragraph)
        for section in append_sections or []:
            if section.get("heading"):
                document.add_heading(str(section["heading"]), level=int(section.get("level", 1)))
            for paragraph in section.get("paragraphs", []):
                document.add_paragraph(str(paragraph))
            for bullet in section.get("bullets", []):
                document.add_paragraph(str(bullet), style="List Bullet")
        document.save(destination)
        return {
            "path": str(destination),
            "kind": "docx",
            "replacements": replaced,
            "appended_sections": len(append_sections or []),
        }

    def export_powerpoint(
        self,
        output_path: str,
        title: str,
        slides: list[dict[str, Any]],
        subtitle: str = "",
    ) -> dict[str, Any]:
        from pptx import Presentation
        from pptx.util import Inches, Pt

        destination = safe_output_path(self.project_root, output_path)
        if destination.suffix.lower() != ".pptx":
            raise ValueError("PowerPoint output path must end with .pptx")
        presentation = Presentation()
        presentation.slide_width = Inches(13.333333)
        presentation.slide_height = Inches(7.5)
        title_slide = presentation.slides.add_slide(presentation.slide_layouts[0])
        title_slide.shapes.title.text = title
        if len(title_slide.placeholders) > 1:
            title_slide.placeholders[1].text = subtitle
        for item in slides:
            slide = presentation.slides.add_slide(presentation.slide_layouts[1])
            slide.shapes.title.text = str(item.get("title", ""))
            body = slide.placeholders[1].text_frame
            body.clear()
            bullets = item.get("bullets") or item.get("paragraphs") or []
            for index, bullet in enumerate(bullets):
                paragraph = body.paragraphs[0] if index == 0 else body.add_paragraph()
                paragraph.text = str(bullet)
                paragraph.level = int(item.get("level", 0))
                paragraph.font.size = Pt(24)
        presentation.core_properties.title = title
        presentation.core_properties.subject = "Generated by Creative Claw"
        presentation.save(destination)
        return {"path": str(destination), "kind": "pptx", "slide_count": len(slides) + 1}

    def edit_powerpoint(
        self,
        path: str,
        replacements: dict[str, str] | None = None,
        append_slides: list[dict[str, Any]] | None = None,
    ) -> dict[str, Any]:
        """Apply explicit text replacements and append standard content slides."""

        from pptx import Presentation
        from pptx.util import Pt

        destination = safe_output_path(self.project_root, path)
        if destination.suffix.lower() != ".pptx" or not destination.is_file():
            raise FileNotFoundError(f"PowerPoint document not found: {destination}")
        presentation = Presentation(destination)
        replacements = replacements or {}
        replaced = 0
        for slide in presentation.slides:
            for shape in slide.shapes:
                if not getattr(shape, "has_text_frame", False):
                    continue
                for paragraph in shape.text_frame.paragraphs:
                    original = paragraph.text
                    updated = original
                    for old, new in replacements.items():
                        occurrences = updated.count(old)
                        if occurrences:
                            updated = updated.replace(old, new)
                            replaced += occurrences
                    if updated != original:
                        paragraph.text = updated
        for item in append_slides or []:
            slide = presentation.slides.add_slide(presentation.slide_layouts[1])
            slide.shapes.title.text = str(item.get("title", ""))
            body = slide.placeholders[1].text_frame
            body.clear()
            for index, bullet in enumerate(item.get("bullets") or item.get("paragraphs") or []):
                paragraph = body.paragraphs[0] if index == 0 else body.add_paragraph()
                paragraph.text = str(bullet)
                paragraph.font.size = Pt(24)
        presentation.save(destination)
        return {
            "path": str(destination),
            "kind": "pptx",
            "replacements": replaced,
            "appended_slides": len(append_slides or []),
            "slide_count": len(presentation.slides),
        }

    def export_excel(
        self,
        output_path: str,
        sheets: list[dict[str, Any]],
    ) -> dict[str, Any]:
        from openpyxl import Workbook
        from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
        from openpyxl.utils import get_column_letter
        from openpyxl.worksheet.page import PageMargins

        destination = safe_output_path(self.project_root, output_path)
        if destination.suffix.lower() != ".xlsx":
            raise ValueError("Excel output path must end with .xlsx")
        workbook = Workbook()
        workbook.remove(workbook.active)
        for sheet_spec in sheets:
            name = str(sheet_spec.get("name", "Sheet"))[:31]
            worksheet = workbook.create_sheet(name)
            rows = sheet_spec.get("rows", [])
            thin = Side(style="thin", color="D7DEE8")
            for row_index, values in enumerate(rows, start=1):
                for column_index, value in enumerate(values, start=1):
                    cell = worksheet.cell(row=row_index, column=column_index, value=value)
                    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
                    cell.font = Font(name="Microsoft YaHei", size=11)
                    cell.border = Border(bottom=thin)
                    if row_index == 1 and sheet_spec.get("header", True):
                        cell.font = Font(name="Microsoft YaHei", size=11, bold=True, color="FFFFFF")
                        cell.fill = PatternFill("solid", fgColor="2F6FED")
                worksheet.row_dimensions[row_index].height = 24 if row_index == 1 else 21
            if rows:
                worksheet.freeze_panes = "A2" if sheet_spec.get("header", True) else None
                max_columns = max(len(row) for row in rows)
                for column_index in range(1, max_columns + 1):
                    width = max(
                        len(str(worksheet.cell(row=row, column=column_index).value or ""))
                        for row in range(1, min(worksheet.max_row, 200) + 1)
                    )
                    worksheet.column_dimensions[get_column_letter(column_index)].width = min(max(width + 2, 10), 42)
                worksheet.sheet_view.showGridLines = False
                worksheet.print_area = f"A1:{get_column_letter(max_columns)}{len(rows)}"
                worksheet.sheet_properties.pageSetUpPr.fitToPage = True
                worksheet.page_setup.orientation = "landscape"
                worksheet.page_setup.paperSize = worksheet.PAPERSIZE_A4
                worksheet.page_setup.fitToWidth = 1
                worksheet.page_setup.fitToHeight = 0
                worksheet.page_margins = PageMargins(
                    left=0.3, right=0.3, top=0.45, bottom=0.45, header=0.15, footer=0.15
                )
        if not workbook.sheetnames:
            workbook.create_sheet("Sheet1")
        workbook.properties.title = "Creative Claw workbook"
        workbook.save(destination)
        return {"path": str(destination), "kind": "xlsx", "sheet_count": len(workbook.sheetnames)}

    def edit_excel(
        self,
        path: str,
        edits: list[dict[str, Any]],
        create_sheets: bool = False,
    ) -> dict[str, Any]:
        """Set explicit cell values/formulas in an existing workbook."""

        from openpyxl import load_workbook

        destination = safe_output_path(self.project_root, path)
        if destination.suffix.lower() != ".xlsx" or not destination.is_file():
            raise FileNotFoundError(f"Excel workbook not found: {destination}")
        workbook = load_workbook(destination)
        try:
            for edit in edits:
                sheet_name = str(edit["sheet"])
                if sheet_name not in workbook.sheetnames:
                    if not create_sheets:
                        raise KeyError(f"Unknown Excel sheet: {sheet_name}")
                    workbook.create_sheet(sheet_name)
                worksheet = workbook[sheet_name]
                worksheet[str(edit["cell"])] = edit.get("value")
            workbook.save(destination)
            return {
                "path": str(destination),
                "kind": "xlsx",
                "edited_cells": len(edits),
                "sheet_count": len(workbook.sheetnames),
            }
        finally:
            workbook.close()
